### PR TITLE
Add a test file to reproduce #84

### PR DESCRIPTION
**Pull request by remohammadi**

### CODE REVIEW

**Comment by remohammadi** [comment]
This is a test file which reproduces #84. It's written to fail the test 😝

And it's written by a not-a-ruby-coder. Would you please help me a little where to look for the source of the problem?
I think the problem is related to [this line](https://github.com/riboseinc/asciidoctor-bibliography/blob/622aecac7527549b51d40c39311fc5ba1295dad6/lib/asciidoctor-bibliography/index.rb#L20). Do you think it is a problem by the CiteProc library, or it can be related to the changes happening in the `formatter.rb`?

**Comment by ronaldtse** [comment]
@remohammadi thanks for the contribution!

@abunashir would you be able to help fix up this one? Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 would you have time to look at this 1 spec failure? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse on it

**Comment by CAMOBAP795** [comment]
Update:

@remohammadi you are a right problem in this place, a full stack trace is:
```
undefined method `bibliography' for #<CSL::Locale en-US>
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/citeproc/ruby/formats/adoc.rb:38:in `aligned_first_field?'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/citeproc/ruby/formats/adoc.rb:31:in `apply_suffix'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/format.rb:176:in `apply'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/format.rb:19:in `format!'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/date.rb:34:in `block in render_date'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/date.rb:33:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/date.rb:33:in `render_date'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:26:in `block in render_block'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:25:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:25:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:25:in `render_block'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:13:in `block in render_choose'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/choose.rb:12:in `render_choose'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/macro.rb:13:in `block in render_macro'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/macro.rb:12:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/macro.rb:12:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/macro.rb:12:in `render_macro'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/text.rb:49:in `render_text'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:17:in `block in render_group'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `render_group'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:17:in `block in render_group'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/group.rb:16:in `render_group'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/layout.rb:13:in `block in render_layout'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/treelike.rb:22:in `each_child'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/layout.rb:12:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/layout.rb:12:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer/layout.rb:12:in `render_layout'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:46:in `render'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/renderer.rb:92:in `render_bibliography'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:69:in `block (2 levels) in bibliography'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:67:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:67:in `block in bibliography'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-1.0.9/lib/citeproc/bibliography.rb:166:in `initialize'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:62:in `new'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:62:in `bibliography'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/citeproc-1.0.9/lib/citeproc/processor.rb:109:in `bibliography'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/index.rb:20:in `render'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/asciidoctor/bibliographer_preprocessor.rb:65:in `block in render_indices'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/asciidoctor/bibliographer_preprocessor.rb:62:in `map'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/asciidoctor/bibliographer_preprocessor.rb:62:in `render_indices'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/asciidoctor/bibliographer_preprocessor.rb:32:in `process_lines'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/lib/asciidoctor-bibliography/asciidoctor/bibliographer_preprocessor.rb:19:in `process'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:565:in `[]'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:565:in `block in parse'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:564:in `each'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:564:in `parse'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/spec/end_to_end_spec.rb:38:in `block (2 levels) in <top (required)>'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:298:in `block (2 levels) in let'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:157:in `block (3 levels) in fetch_or_store'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:157:in `fetch'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:157:in `block (2 levels) in fetch_or_store'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-support-3.7.1/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:156:in `block in fetch_or_store'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch_or_store'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:298:in `block in let'
/Users/camobap/Developers/Projects/riboseinc/asciidoctor-bibliography/spec/end_to_end_spec.rb:51:in `block (2 levels) in <top (required)>'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
/Users/camobap/.rbenv/versions/2.5.4/bin/rspec:23:in `load'
/Users/camobap/.rbenv/versions/2.5.4/bin/rspec:23:in `<top (required)>'
/Users/camobap/.gem/ruby/2.5.0/gems/ruby-debug-ide-0.7.0.beta7/lib/ruby-debug-ide.rb:100:in `debug_load'
/Users/camobap/.gem/ruby/2.5.0/gems/ruby-debug-ide-0.7.0.beta7/lib/ruby-debug-ide.rb:100:in `debug_program'
/Users/camobap/.gem/ruby/2.5.0/gems/ruby-debug-ide-0.7.0.beta7/bin/rdebug-ide:187:in `<main>'
```

Fix will be submitted soon

**Comment by ronaldtse** [comment]
@remohammadi the fix and your provided test have been merged in #89. Thank you again for your report and contribution!!

**Pull request closed without merging**
